### PR TITLE
Updated to latest SDK dependencies.

### PR DESCRIPTION
**Pull request by ducanbeu**
https://app.clickup.com/t/86aypddu4

You may need to run a quick `npm i` before you run `npm run start`. Change the country field and start typing an address. Make sure you get some autocomplete options, choose one and make sure that it fills in the appropriate fields. Oh, you'll also want to insert your own website key in `Autocomplete.js`, don't forget to do that.

### CODE REVIEW

**Comment by ducanbeu** [comment]
Hold off on reviewing this for just a sec.

**Comment by ducanbeu** [comment]
Ok now give it a review. Thanks!

**Comment by smartyandrewb** [comment]
The tool is working great! nicely done. I just had a few things I found. The validate address button isn't working for me. I think the function passed in doesn't exist.  Also just a thought, do we want to conditionally render the label names depending on if its US or International? if not no worries. One last thing that might be nice to fix, the tool always sends a request when the address line is empty which gives a 422 error.

**Comment by ducanbeu** [comment]
Those are both items that don't exact pertain to this card but we can make some additional cards for those

**Review by smartyandrewb — APPROVED** [review]

**Pull request merged**
